# Colors (Nord)

# Default colors
[colors.primary]
background = '#282c34' # 1
foreground = '#b4befe' # 2

[colors.cursor]
text    = '#181819'
cursor  = '#e2e2e3'

# Normal colors
[colors.normal]
black   = '#262626' # 4
red     = '#ff5f5f' # 5
green   = '#9ed072'
yellow  = '#e7c664'
blue    = '#b4befe' # 1 2851a4
magenta = '#878787'
cyan    = '#b4befe' # 3
white   = '#7f8490'

# Bright colors
[colors.bright]
black   = '#eeeeee'
red     = '#ff6077'
green   = '#b4befe' # 7
yellow  = '#d7af5f' # 6
blue    = '#b4befe' # 8
magenta = '#d75f00'
cyan    = '#005faf'
white   = '#e3e3e3' # 2
